### ISSUE TITLE
flags + config file

### ISSUE THREAD

**Issue by swill** [integrii/flaggy#24]
Ideally it would be possible to define the config via either a config file or via flags.  If the same flag is present in both the config file and the flags, the flags take precedence.

I find that being able to use a combination of config files and flags makes for a very robust system.  There is some config which makes sense to live with the application in a config file, while other types of config make the most sense to be passed via a flag.

**Comment by integrii** [comment]
Flaggy actually makes this pretty easy! You can create your configuration spec, then pass the parameters in as pointers to flaggy's flag functions.  If the user specifies nothing, the default from the configuration struct is used.

```golang
package main

import "github.com/integrii/flaggy"

type Config struct {
	Key string
}

var cfg = Config{
	Key: "default config value",
}

func init() {
	flaggy.String(&cfg.Key, "k", "key", "Test key")
	flaggy.Parse()
}

func main() {
	print(cfg.Key)
}
```

**Comment by swill** [comment]
I don't see how this is loading the config from a file.  Is that what you are illustrating here?

**Comment by integrii** [comment]
To load or save the config from a file, just implement and call a `Save()` and `Load()` method on the `Config` struct here.  As long as you call `cfg.Load()` before `flaggy.Parse()`, you will have default values from a file.

**Comment by integrii** [comment]
Closin' this.  To be fully verbose here for anyone that comes later looking to use a configuration file with flaggy, the code would look something like this:

```go
package main

import (
	"encoding/json"
	"io/ioutil"

	"github.com/integrii/flaggy"
)

type Config struct {
	Key string
}

func (c *Config) Save(fileName string) error {
	b, err := json.Marshal(c)
	if err != nil {
		return err
	}
	return ioutil.WriteFile(fileName, b, 0750)
}

func (c *Config) Load(fileName string) error {
	b, err := ioutil.ReadFile(fileName)
	if err != nil {
		return err
	}
	return json.Unmarshal(b, c)
}

var cfg = Config{
	Key: "default config value",
}

const configFile = "config.json"

func init() {
	err := cfg.Load(configFile)
	if err != nil {
		panic(err)
	}
	flaggy.String(&cfg.Key, "k", "key", "Test key")
	flaggy.Parse()
}

func main() {
	print(cfg.Key)
}
```
