### ISSUE TITLE
How do you use the ShowHelpOnUnexpected option for DefaultParser?

### ISSUE THREAD

**Issue by atc0005** [integrii/flaggy#47]
I tried using the option as shown here:

https://github.com/integrii/flaggy/blob/master/README.md#recommended-program-structure

and with tag `1.2.2` (425304205580254c6ea87908f35848c46eb99d5e) I *do* see the help output when I use an invalid flag, but *only* if I don't specify a value for the flag when I specify the flag.

Example program:

```golang
package main

import (
	"fmt"

	"github.com/integrii/flaggy"
)

func main() {

	optBool := false
	optIntegerTestVar := 1
	optStringTestVar := "My test string"

	flaggy.SetName("Test")
	flaggy.SetDescription("Short example to illustrate issue")

	flaggy.DefaultParser.ShowHelpOnUnexpected = true

	// Add flags
	flaggy.Bool(&optBool, "bo", "bool", "Boolean test option")
	flaggy.Int(&optIntegerTestVar, "int", "inttest", "Integer test option")
	flaggy.String(&optStringTestVar, "str", "stringtest", "String test option")

	// Parse the flag
	flaggy.Parse()

	fmt.Printf("%v\n", optBool)
	fmt.Printf("%v\n", optIntegerTestVar)
	fmt.Printf("%v\n", optStringTestVar)

}
```

Example usage:

```ShellSession
$ go run main.go -warning
Test - Short example to illustrate issue

  Flags:
       --version  Displays the program version string.
    -h --help  Displays help with available flag, subcommand, and positional value parameters.
    -bo --bool  Boolean test option
    -int --inttest  Integer test option (default: 1)
    -str --stringtest  String test option (default: My test string)

Expected a following arg for flag warning, but it did not exist.
exit status 2
```

```ShellSession
$ go run main.go -warning=no
false
1
My test string
```

```ShellSession
$ go run main.go --warning=no
false
1
My test string
```

**Comment by integrii** [comment]
I need to look into this.  This may be a bug.

**Comment by ravenpride** [comment]
@integrii Is there any progress fixing the bug? If you are busy, I could possibly help.

**Comment by integrii** [comment]
I keep meaning to look at this... I welcome any help @ravenpride!

**Comment by ravenpride** [comment]
The issue should be fixed. Please see PR #54.

**Comment by integrii** [comment]
I took a look at your stuff @ravenpride and I appreciate your help.  However, I dove in and I think PR #55 fixes this in a slightly more simple way.  Let me know what you guys think and I'll merge it.

**Comment by integrii** [comment]
You can actually see here (in the current live code) that I put in a comment describing what should go below, but never actually wrote it!  The PR just fills it in:

https://github.com/integrii/flaggy/blob/master/subCommand.go#L163

**Comment by ravenpride** [comment]
I see, but could you please have a look at my comments regarding PR #55 ?

**Comment by integrii** [comment]
Launched in release 1.4.0!
