### ISSUE TITLE
Incorrect parsing of bool flags on subcommands

### ISSUE THREAD

**Issue by freb** [integrii/flaggy#57]
Bool flaggs specified on the parser are handled differently than those set on the subcommand. I couldn't find any documentation on why this should be the case, so I'm assuming there is a bug.

On the parser, you're able to pass a flag like `-f`, and the variable passed into `flagg.Bool()` will be set as true. However, if you define `-f` on a subcommand, passing `-f` to the program errors with: `Expected a following arg for flag f, but it did not exist.`

I've created a minimal example: <https://play.golang.org/p/ScB7PMv9rZ5>

I tried tracking this down. I discovered that the subcommand passed to the [flagIsBool](https://github.com/integrii/flaggy/blob/597c2dd3baff62f198a75f01b414cab6a412834e/flag.go#L412) function does not contain the bool flag defined on the subcommand.

**Comment by freb** [comment]
Thanks for expanding on this. I had just run into the issue you describe but hadn't yet diagnosed it was related to boolean flags. In my case:

This failed:

```
./app mainSubCommand subOperation --string1 TEXT1 --boolflag=true --string2 TEXT2
```

But this worked:

```
./app mainSubCommand subOperation --string1 TEXT1 --boolflag=true --string2=TEXT2
```

But as you described, this also worked:

```
./app mainSubCommand subOperation --boolflag --string1 TEXT --string2 TEXT2
```

**Comment by ethanmoffat** [comment]
@freb I was able to fix it for myself (PR submitted), do you want to check if that fixes it for your case too?

**Comment by freb** [comment]
I tested it and it works for all my corner cases. Thanks, much appreciated!

**Comment by integrii** [comment]
You guys are the best - thanks for attacking this and using flaggy.  The fixed has been merged so i am closing this out!
